ref-data:
  engine-types: Бензиновий, Дизельний, Гібридний

  fuel-types:
    бензин:
      - А-95
      - А-98
      - А-100
    дизель:
      - зимовий
      - літній
      - арктичний
    електрика: []